# the upstream component nginx needs to connect to
upstream educa {
	server unix:///tmp/educa.sock;
}


'''
We tell NGINX to listen on port 80.
We set the server name to both www.educaproject.com and
educaproject.com. NGINX will serve incoming requests for both domains.
We specify that everything under the / path has to be routed to the educa socket
(uWSGI). We also include the default uWSGI configuration params that come
with NGIN
'''

server {
	listen 80;
	server_name www.educaproject.com educaproject.com;
	location / {
		include /etc/nginx/uwsgi_params;
		uwsgi_pass educa;
	}
	
	location /static/ {
		alias /home/projects/educa/static/;
	}
	
	location /media/ {
		alias /home/projects/educa/media/;
	}
}

'''
he primary NGINX configuration file is located at /etc/nginx/nginx.conf. It includes
any configuration files found under /etc/nginx/sites-enabled/. To make NGINX load
your custom configuration file, open the shell and create a symbolic link as follows:
sudo ln -s /home/projects/educa/config/nginx.conf /etc/nginx/sitesenabled/educa.conf
Replace /home/projects/educa/ with your project's absolute path. Then open a shell
and run uWSGI if you are not running it yet:
uwsgi --ini config/uwsgi.ini
Open a second shell and run NGINX with the following command:
service nginx start
'''


'''
Edit your /etc/hosts file and add the following lines to it:
127.0.0.1 educaproject.com
127.0.0.1 www.educaproject.com
'''





